apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers: 
  - name: redis
    image: redis:5.0.4
    command:
      - redis-server
      - "/redis-master/redis.conf"
    env:
    - name: MASTER   # Redis will automatically read the environment variable
      value: "true"
    ports:
    - containerPort: 6379   # Expose container port 6379, protocol tcp, no port name specified
    resources:
      limits:  # Resource limits for the container
        cpu: "0.1"
    volumeMounts:
    - mountPath: /redis-master-data
      name: data
    - mountPath: /redis-master
      name: config
  volumes:
    - name: data     # Temporary directory for writing Redis cache, created and destroyed with the pod lifecycle
      emptyDir: {}
    - name: config
      configMap:
        name: redis-configmap  # ConfigMap name
        items:
        - key: redis-config
          path: redis.conf   # File name after being mounted into the pod